### ISSUE TITLE
Could you please create a Maven version of this project?

### ISSUE THREAD

**Issue by ghost** [skate056/spring-security-oauth2-google#1]

**Comment by skate056** [comment]
Apologies for the late reply. I will give this a go.

**Comment by crazyguyonabike** [comment]
I am interested in this as well. I have started it up with the gradle feature to generate a pom.xml but am having trouble getting all the beans instantiated properly when starting up the application context. As far as I can tell the GoogleProfile has changed (I have modified my local copy to reflect the changes. Also whats very confusing from the Spring Security extension perspective is that I'm not clear where you're youre supposed to call getGoogleProfile to create an actual logged in user.

**Comment by skate056** [comment]
Implemented https://github.com/skate056/spring-security-oauth2-google/pull/4
